CREATE TABLE IF NOT EXISTS registrations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  registration_type ENUM('existing', 'new') NOT NULL,
  existing_nhf_number VARCHAR(20) NULL,
  employment_status ENUM('active', 'retired') NOT NULL,
  surname VARCHAR(60) NOT NULL,
  other_names VARCHAR(100) NOT NULL,
  gender ENUM('male', 'female') NOT NULL,
  ippis_number VARCHAR(30) NOT NULL,
  staff_id_number VARCHAR(30) NOT NULL,
  posting_location VARCHAR(100) NOT NULL,
  geopolitical_zone ENUM('northcentral', 'northeast', 'northwest', 'southeast', 'southsouth', 'southwest') NOT NULL,
  date_of_birth DATE NOT NULL,
  mobile_number VARCHAR(15) NOT NULL,
  email_address VARCHAR(120) NOT NULL,
  bank_name VARCHAR(120) NOT NULL,
  account_number VARCHAR(20) NOT NULL,
  nnn_number VARCHAR(20) NOT NULL,
  nhf_number VARCHAR(20) NOT NULL,
  employment_date DATE NOT NULL,
  monthly_salary DECIMAL(12,2) NOT NULL,
  next_of_kin_name VARCHAR(120) NOT NULL,
  next_of_kin_address VARCHAR(200) NOT NULL,
  next_of_kin_phone VARCHAR(15) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_nhf_number (nhf_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
